### ISSUE TITLE
Help me solve this issue

### ISSUE THREAD

**Issue by SiongokBrian** [ibrahimhabibeg/stadium-go-client#1]
![Capture1](https://github.com/ibrahimhabibeg/stadium-go-client/assets/57943998/f35240d1-04af-484e-96f7-7cee7cd45d9b)

how do i clear this error

**Comment by ibrahimhabibeg** [comment]
Actually, this is not a native Android app. This is a mobile app built using react native. Thus, you don't have to use Android Studio to run it.

To use the app, follow these steps
1 - Install Node js on your device. https://nodejs.org/en/download
2 - Clone the app 
`git clone https://github.com/ibrahimhabibeg/stadium-go-client.git`
3 - Change the directory to the app directory
`cd stadium-go-client`
4 - Start the app in development mode
`npm run start`

The app will now start running. You can run the app in either an emulator or use Expo Go to run the app on your phone.

You can use whatever IDE you like to develop the app like vs code, atom, sublime, etc.

Note that you need to also set up the server-side app for the mobile app to provide functionality. The server app is in this repo https://github.com/ibrahimhabibeg/stadium-go-server
